### ISSUE TITLE
ユーザの新規登録は"Register"より"Signup"の方が自然そう

### ISSUE THREAD

**Issue by funator26** [kooooichi24/sb-library-frontend#4]

**Comment by kooooichi24** [comment]
自分もSignUpと思って修正しましたが、英語を調べたらRegisterが一般的みたいです、、、

https://eikaiwa.dmm.com/uknow/questions/40460/

**Comment by funator26** [comment]
そのサイトでもこういう↓意見もあるから「Registerの方が一般的」とも断定できなそう
<img width="722"  border="3" alt="スクリーンショット 2020-07-09 7 49 51" src="https://user-images.githubusercontent.com/66573665/86978043-dfbbee00-c1b8-11ea-90e7-30e1378a43a8.png">

[意味的には同じっぽい](https://hinative.com/ja/questions/1115)しどっちでもいいのかも知れないけど、
Webサービスのボタン表示でRegisterって見たことないなぁと思った

**Comment by funator26** [comment]
Register.vueだと「何の登録のためのコンポーネント？」ってなっちゃうから、
Signup.vueか、Registを使うのであればRegistUser.vueが明確かなぁ

ただ、RegistUserだと「ユーザ自身が自分を新規会員として登録する」というよりも
「システムが管理者としてユーザを登録する」ように思われる気がする

**Comment by kooooichi24** [comment]
英語勉強します；；
